### ISSUE TITLE
SymfonySetList::SYMFONY_43 causes: Analyze error: "Class PHPUnit\Framework\TestCase not found."

### ISSUE THREAD

**Issue by Bilge** [rectorphp/rector-symfony#62] opened 2021-11-11 16:31 UTC
Even on the older Rector v0.11.60, `SymfonySetList::SYMFONY_43` causes almost every file to emit the following error once analysis completes (`src/Kernel.php` varies to all the other project file names between each error message emitted):

>  [ERROR] Could not process "src/Kernel.php" file, due to:
         "Analyze error: "Class PHPUnit\Framework\TestCase not found.". Include your files in
         "$parameters->set(Option::AUTOLOAD_PATHS, [...]);" in "rector.php" config.
         See https://github.com/rectorphp/rector#configuration".

I've tried setting `Option::AUTOLOAD_PATHS`, although I don't know what I should set it to. I've tried setting `--autoload-file` on the command line, since I'm running inside Docker so perhaps rectorphp/rector#5104 might apply, but none of these changes fixes the issue. No prior Symfony set list needs this additional configuration, nor does the one after (SYMFONY_44). 

The error is particularly strange since I am only running Rector on the `src` dir and there should be no references to any test classes in there.

Note: this may be a duplicate of #43, where the reporter managed to narrow it down to this specific Rector: `SimplifyWebTestCaseAssertionsRector`, which I can now confirm is the source of the problem in this set.

**Comment by TomasVotruba** [comment] 2021-11-12 09:44
Hi, 

thanks fore reporting :+1: 
Could you share minimal reproducible repository on Github so we can examine the bug and then verify the fix? 
With Rector 0.12 version at least.

Thank you

**Comment by come-nc** [comment] 2021-11-16 10:53
Hello, I am not sure if this is the same issue, but I get:
```
[ERROR] Could not process "lib/private/Mail/Mailer.php" file, due to:                                                  
         "Analyze error: "Class Psr\EventDispatcher\StoppableEventInterface not found.". Include your files in          
         "$parameters->set(Option::AUTOLOAD_PATHS, [...]);" or "$parameters->set(Option::BOOTSTRAP_FILES, [...]);" in   
         "rector.php" config.                                                                                           
         See https://github.com/rectorphp/rector#configuration". 
```

On almost all files when running rector on nextcloud/server codebase.
I tried `$parameters->set(Option::AUTOLOAD_PATHS, [__DIR__ . '/3rdparty']);` but that does not fix the issue.

It does not seem to depend upon which set I use, which is why I’m not sure if this is the same as this ticket.

**Comment by samsonasik** [comment] 2021-11-29 03:36
Looking at the documentation, you may need to define one by one autoload files or use `BOOTSTRAP_FILES` config.

https://github.com/rectorphp/rector/blob/main/docs/static_reflection_and_autoload.md#static-reflection-and-autoload

**Comment by samsonasik** [comment] 2021-12-17 03:04
Documentation was updated for Class not found troubleshooting https://github.com/rectorphp/rector/blob/main/docs/static_reflection_and_autoload.md#dealing-with-class--was-not-found-while-trying-to-analyse-it to use `"files"` config. 

Please give a try.

**Comment by come-nc** [comment] 2021-12-20 08:43
Adding the flie StoppableEventInterface.php directly in autoload>files and using composer dump-autoload does fix the error.
It still feels like a bug since rector is the only tool needing this manipulation.

**Comment by samsonasik** [comment] 2021-12-20 09:48
Rector uses `PHPStan\Reflection\ReflectionProvider` for it, so it rely to internal PHPStan. I am closing it as answered and the solution provided and works.

**Closed by samsonasik** 2021-12-20 09:48 UTC

**Comment by come-nc** [comment] 2021-12-20 10:49
This workaround is not satisfying, in the end I had to add 30 files in this array, which I have to remove when using an other tool than rector to avoid problems.

Should I open a bug at phpstan then?
