### ISSUE TITLE
MessageHandlerInterfaceToAttributeRector False positive

### ISSUE THREAD

**Issue by jambonfarci** [rectorphp/rector-symfony#535] opened 2023-10-12 10:17 UTC
Rector demo link : [https://getrector.com/demo/1e2e5f56-7ca6-40fb-94bf-a1d1cfa13059](https://getrector.com/demo/1e2e5f56-7ca6-40fb-94bf-a1d1cfa13059)

The changes don't match with the rule applied : 
![image](https://github.com/rectorphp/rector-symfony/assets/1522511/c296bcfb-6b74-4b9e-a32d-54e9da2954f8)

**Comment by TomasVotruba** [comment] 2023-10-12 14:21
Thank you for your report and demo link!

We'll need a failing test case in a pull-request, so we have it covered in Rector.
You can click "Create a Test" button at demo page.

**Comment by jambonfarci** [comment] 2023-10-12 14:25
Thanks for your quick reply !
I'll try to covered the test as soon as possible.

**Comment by jambonfarci** [comment] 2023-10-12 15:58
I've narrowed down the rules to be more precise : [https://getrector.com/demo/19b6ba38-d974-4095-a5f2-576cad86171f](https://getrector.com/demo/19b6ba38-d974-4095-a5f2-576cad86171f)

I'll try to make a PR with a failing test next.

**Comment by stefantalen** [comment] 2023-10-13 09:59
Looks like an issue with combined rules.

Just using the `MessageHandlerInterfaceToAttributeRector` results in no changes 🙂 

Can you narrow down the rules instead of using a set?

**Comment by jambonfarci** [comment] 2023-10-13 13:47
Indeed, i've found the rules  : [https://getrector.com/demo/e761b19d-3501-4f1d-85b1-51a9d1fca87c](https://getrector.com/demo/e761b19d-3501-4f1d-85b1-51a9d1fca87c)

The `RenameClassRector` rule is part of the Symfony6.2 Set.

**Comment by stefantalen** [comment] 2023-10-13 17:43
@TomasVotruba should this be considered a `rector/rector` issue?

**Comment by samsonasik** [comment] 2023-10-14 01:53
@stefantalen it seems yes, I will look into it

**Comment by samsonasik** [comment] 2023-10-14 06:05
Looking at how transformation of `IsGranted`, it  tries to rename:

https://github.com/rectorphp/rector-symfony/blob/873458ca73a73f9becd1680963a347bbcb8e5f43/config/sets/symfony/symfony62.php#L24-L25

while it **still** an `Annotation`. On other hand, the `sensiolabs` is changing to attribute on `Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted` instead (old class).

https://github.com/rectorphp/rector-symfony/blob/873458ca73a73f9becd1680963a347bbcb8e5f43/config/sets/sensiolabs/annotations-to-attributes.php#L14

so, the fix need to be:

- don't rename `SpacelessPhpDocTagNode` annotation (as current implementation)
- on auto import, ensure that use statement is not part of renaming process.

so, if annotation is skipped, then annotation to attribute will be applied, after that, attribute to new attribute rename will be executed later.

It seems need dedicated configured tests.

**Comment by samsonasik** [comment] 2023-10-14 06:18
Here annotation to attribute with rename applied (without autoImport enabled)

https://getrector.com/demo/6bf4d5c3-882c-4b09-9bcf-323ffb278a19

so the fix to be: don't remove use statement when use statement part of rename list old name.

**Comment by samsonasik** [comment] 2023-10-14 11:19
Hm.., on investigating, it seems rename annotation is allowed, just currently applied only on specific symfony assert, doctrine, and serializer:

https://github.com/rectorphp/rector-src/blob/d55a35bcdede830d3927de1c11e0f7f0d12ee9e4/packages/BetterPhpDocParser/PhpDocManipulator/PhpDocClassRenamer.php#L36-L38

that's why process is overlapped, which annotation not renamed, but use statement removed during auto import.

**Comment by samsonasik** [comment] 2023-10-14 11:32
I created test PR for it:

- https://github.com/rectorphp/rector-src/pull/5168

**Comment by samsonasik** [comment] 2023-10-15 03:36
Resolved at https://github.com/rectorphp/rector-src/pull/5168

**Comment by samsonasik** [comment] 2023-10-16 06:54
Re-open to rework

**Comment by samsonasik** [comment] 2023-10-16 07:17
Reworking on https://github.com/rectorphp/rector-src/pull/5178

**Comment by samsonasik** [comment] 2023-10-29 02:53
After back and forth checking it, I think change to attribute should be executed first, then rename to be applied, see

https://getrector.com/demo/610b5bb8-b1a0-4179-be19-21fcdd374415

so on this case, the `AnnotationToAttributeRector` should be registered to `symfony62.php` early before rename.

The issue is then on auto import, when change to attribute then rename attribute name, the import removed with `$rectorConfig->importNames()` applied, see

https://getrector.com/demo/4c8f80f5-9050-4b6b-b58e-93034ea3d45b

**Comment by samsonasik** [comment] 2023-10-29 03:01
I create test case at https://github.com/rectorphp/rector-src/pull/5213

**Comment by samsonasik** [comment] 2023-10-29 11:10
Resolved with 2 PRs:

- https://github.com/rectorphp/rector-src/pull/5213
- https://github.com/rectorphp/rector-symfony/pull/544

**Summary:** 

The configuration needs to change to attribute first before rename, at PR: 

- https://github.com/rectorphp/rector-src/pull/5213

which require to check name is from Attribute rename when auto import enabled, which require PR on rector-src 

- https://github.com/rectorphp/rector-src/pull/5213

**Comment by samsonasik** [comment] 2023-10-29 20:47
@jambonfarci On big list `SymfonyLevelSetList::UP_TO_SYMFONY_63`, the use statement removal seems still happen, I suggest for your use case, apply per SetList first, then enable auto import later after it changed, so first:

https://getrector.com/demo/ca9eab33-2e10-4b23-9487-b1f89cae12e9

Before enable auto import:

https://getrector.com/demo/5cb42bbc-22c1-4a21-bc33-75b7b99efc1c

**Comment by samsonasik** [comment] 2023-11-01 18:09
Ok, it seems the issue is when there is already existing attribute defined (there is removed use statement)

https://getrector.com/demo/4a7aaef0-ea62-4274-93c1-c58aafed8f7a

when no attribute yet defined, it seems working ok (the use statement is replaced with new one)

https://getrector.com/demo/c2156b4e-6818-4885-8381-bf6197f56e56

it seems when rename a node, the service to collect the named node need to be collected so it can be used on PostRector to only remove when there is renamed name equal.

Re-open :)

**Closed** 2023-11-02 03:17 UTC
