### ISSUE TITLE
Symfony 6.1 - `AsCommand` addition not correct when using constants in name

### ISSUE THREAD

**Issue by etshy** [rectorphp/rector-symfony#638] opened 2024-07-04 12:53 UTC
(I'll apologize here as I'll likely report a few bugs while I'm upgrading projects)

When using constants in a `Command` name like this
```php
protected static $defaultName = 'app:'.Entity::COMMAND1.':process';
```
The name is not moved to the `AsCommand` attributes, making it not valid.
```php
#[AsCommand(description: 'blabla')]
```

When it could be created like this
```php
#[AsCommand(name: 'app:'.Entity::COMMAND1.':process', description: 'blabla')]
```

The name should take whatever is between `$defaultName = ` and the semi-colon.

ps : I'm not sure why these commands was even made that way, but as they're dynamically run by other process I guess it was to be sure of the command to run

**Comment by TomasVotruba** [comment] 2024-07-04 13:44
Thanks for reporting!

/cc @JohJohan

**Comment by TomasVotruba** [comment] 2024-07-05 09:17
> (I'll apologize here as I'll likely report a few bugs while I'm upgrading projects)

Btw, this is mostly welcomed :) we need testing in the wild and often polish existing rules based on reports like your. Thank you for your time and patience :+1:

**Comment by TomasVotruba** [comment] 2024-07-05 09:17
Looking into this...

**Comment by TomasVotruba** [comment] 2024-07-05 09:53
Fixed in: https://github.com/rectorphp/rector-symfony/pull/643 :+1:

**Closed** 2024-07-05 09:53 UTC

**Comment by etshy** [comment] 2024-07-05 12:12
That was fast !
I'll try it soon on the next project I migrate

**Comment by etshy** [comment] 2024-07-05 12:48
Agh, I can't test because `dev-main` of `rector/rector-symfony` need `php:8.2` while we're still in `php:8.1` (planning to update to php 8.4 when it's released in a few months).

I'll make a light symfony project at home to try it.

**Comment by TomasVotruba** [comment] 2024-07-05 12:56
The `dev-main` of rector/rector. This is only meta package that is included in the release.

**Comment by etshy** [comment] 2024-07-08 13:11
Good news, it works, thanks !
Not really important but for some reason it creates the `name` param after the `description` param now though.

**Comment by TomasVotruba** [comment] 2024-07-08 13:15
@etshy Thanks for quick testing :+1: 

> Not really important but for some reason it creates the name param after the description param now though.

That's a bit annoying. Could you share exact test fixture where this happens via https://getrector.com/demo?

**Comment by etshy** [comment] 2024-07-08 13:27
Sure.
https://getrector.com/demo/c1d3944a-cc30-4236-a08e-9f5d02f14ea6
I made it as light as possible but still reproducing the issue.

Noticed the description method stays even if empty after refactoring too.

ps : This sandbox is amazing btw

**Comment by samsonasik** [comment] 2024-07-08 13:37
it seems moving `self::command` to class attribute cause error, is that the issue, ref https://3v4l.org/p9206

**Comment by samsonasik** [comment] 2024-07-08 13:38
hm.., when COMMAND constant exists, it seems still working https://3v4l.org/1lS5n

**Comment by samsonasik** [comment] 2024-07-08 13:40
so, the issue is calling `self::command` instead of `self::COMMAND` ? 

working https://3v4l.org/1lS5n 
not working (constant not exists) https://3v4l.org/qTKeQ

**Comment by TomasVotruba** [comment] 2024-07-08 13:49
@etshy 

> ps : This sandbox is amazing btw

Awesome to hear that :pray: 

@samsonasik Thanks for checking. Could you add fix for this one so `name` is always first?

**Comment by TomasVotruba** [comment] 2024-07-08 13:49
@etshy 

> ps : This sandbox is amazing btw

Awesome to hear that :pray: 

@samsonasik Thanks for checking. Could you add fix for this one so `name` is always first?

**Comment by etshy** [comment] 2024-07-08 13:59
Sorry for the mistake about the constant case in demo, my bad.
That doesn't change the order of the param though and rector doesn't change the case

**Comment by samsonasik** [comment] 2024-07-08 14:11
@etshy what the issue, is order argument matter in symfony?

**Comment by etshy** [comment] 2024-07-08 14:14
Oh no like I said it's not that important, just generating a weak warning on phpstorm.
Nothing mandatory or whatever.

**Comment by samsonasik** [comment] 2024-07-08 14:27
@TomasVotruba I think it is fine as is due to multiple rules apply and it doesn't change the functionality

**Comment by TomasVotruba** [comment] 2024-07-08 16:05
I see. It happens when 2 rules are run together:

* [CommandConfigureToAttributeRector](https://github.com/rectorphp/rector/blob/main/docs/rector_rules_overview.md#commandconfiguretoattributerector)
* [CommandPropertyToAttributeRector](https://github.com/rectorphp/rector/blob/main/docs/rector_rules_overview.md#commandpropertytoattributerector)

Looking into it...

**Comment by TomasVotruba** [comment] 2024-07-08 16:39
Here is my attempt :) https://github.com/rectorphp/rector-symfony/pull/644
