### ISSUE TITLE
Issue with RedirectToRouteRector rule

### ISSUE THREAD

**Issue by cvele** [rectorphp/rector-symfony#102] opened 2022-01-16 19:49 UTC
```php

namespace App\Controller\Admin;

use EasyCorp\Bundle\EasyAdminBundle\Controller\AbstractDashboardController;
use EasyCorp\Bundle\EasyAdminBundle\Router\AdminUrlGenerator;
use Symfony\Component\Routing\Annotation\Route;

class DashboardController extends AbstractDashboardController
{
    private AdminUrlGenerator $adminUrlGenerator;

    public function __construct(AdminUrlGenerator $adminUrlGenerator)
    {
        $this->adminUrlGenerator = $adminUrlGenerator;
    }
    
    /**
     * @Route("/admin")
     */
    public function index(): Response
    {
        return $this->redirect($this->adminUrlGenerator->setController(UserCrudController::class)->generateUrl());
    }
}
```

```php

use Rector\Symfony\Set\SymfonyLevelSetList;
use Symfony\Component\DependencyInjection\Loader\Configurator\ContainerConfigurator;

return static function (ContainerConfigurator $containerConfigurator): void {
    $containerConfigurator->import(SymfonyLevelSetList::UP_TO_SYMFONY_54);
};
```

Results in: 
```diff
    ---------- begin diff ----------
@@ @@

 class DashboardController extends AbstractDashboardController
 {
-    private AdminUrlGenerator $adminUrlGenerator;
-
-    public function __construct(AdminUrlGenerator $adminUrlGenerator)
-    {
-        $this->adminUrlGenerator = $adminUrlGenerator;
-    }
-
     /**
      * @Route("/admin")
      */
     public function index(): Response
     {
-        return $this->redirect($this->adminUrlGenerator->setController(UserCrudController::class)->generateUrl());
+        return $this->redirectToRoute(null);
     }
 }
    ----------- end diff -----------
```

 With  error:

```
[ERROR] Could not process "/path/vendor/rector/rector/vendor/rector/rector-symfony/src/Rector/MethodCal/RedirectToRouteRector.php" file, due to:  Undefined offset: 0". On line: 80
```

**Comment by TomasVotruba** [comment] 2022-01-16 20:06
Thank you for your report!

We'll need an isolated failing demo link from: http://getrector.org/demo,
that way we can reproduce the bug. Could you create one and share?

**Comment by cvele** [comment] 2022-01-16 20:39
@TomasVotruba I've tried, but no output is generated. I assumed that this is related to exception.
However here it is: https://getrector.org/demo/1ec770c6-4e8f-6e2e-a0e1-9789b549589a

**Comment by TomasVotruba** [comment] 2022-01-16 21:14
I see, thanks.

Could you send a failing test case in a pull-request, so we have it covered in `RedirectToRouteRectorTest`?

**Comment by samsonasik** [comment] 2022-03-06 08:04
@cvele I can't reproduce it with the following fixture:

```php
<?php

namespace Rector\Symfony\Tests\Rector\MethodCall\RedirectToRouteRector\Fixture;

use EasyCorp\Bundle\EasyAdminBundle\Controller\AbstractDashboardController;
use EasyCorp\Bundle\EasyAdminBundle\Router\AdminUrlGenerator;

final class SkipFromAdminUrlGenerator extends AbstractDashboardController
{
    public function __construct(private readonly AdminUrlGenerator $adminUrlGenerator)
    {
    }

    public function someAction()
    {
        return $this->redirect(
            $this->adminUrlGenerator
                 ->setController(UserCrudController::class)->generateUrl()
        );
    }
}
```

I am closing it, feel free to provide a failing fixture to https://github.com/rectorphp/rector-symfony/tree/main/tests/Rector/MethodCall/RedirectToRouteRector/Fixture if you still have issue. Thank you.

**Closed by samsonasik** 2022-03-06 08:04 UTC

**Comment by jonnyeom** [comment] 2023-01-24 21:59
Rector seems to now just 
```php
    return $this->redirectToRoute(null);
```

I am just skipping for now
```php
    $rectorConfig->skip([
        // Bug with EasyAdmin, see https://github.com/rectorphp/rector-symfony/issues/102
        RedirectToRouteRector::class,
    ]);
```
